### ISSUE TITLE
Feature request: respect .gitignore etc at the topdir

### ISSUE THREAD

**Issue by laoshaw** [boyter/scc#361] opened 2022-12-19 23:42 UTC
if I ran scc at the root of my git repo it works well, and much faster than cloc, tokei.

when I go to the sub directories, I found my python lines are in huge numbers, turns out the modules under .venv in this sub-directory is counted in though my .gitignore excludes it.

can scc check .gitignore etc as how git does?

**Comment by boyter** [comment] 2022-12-22 22:12
Cheers. A reproducible test case always makes this easier.

**Comment by boyter** [comment] 2024-04-30 06:38
OK this should now be resolved in current master branch due to the inclusion of proper .gitignore support.

**Closed by boyter** 2024-04-30 06:38 UTC
Labels: bug
