### ISSUE TITLE
false statistics about a language that is not actually present in repo.

### ISSUE THREAD

**Issue by fahadhk** [boyter/scc#82] opened 2019-06-19 09:14 UTC
**Describe the bug**
When I run `scc` a command line directly from repo directory i am getting correct statistics but when I run it like mentioned below I also get ASP.NET in statistics. How come that can happen?

**To Reproduce**

1. using `scc` as command line.
2. command line arguments. `$ scc /path/to/a/repo`

**Expected behavior**
I expect it to show statistics about Golang, markdown, makefile and gitignore only.

**Desktop (please complete the following information):**
 - OS: [Linux Ubuntu 19.04]

**Comment by dbaggerman** [comment] 2019-06-19 09:44
I'm able to reproduce this. Looks like `.git` directories aren't being filtered out when using an absolute path.

ASP.NET lists `.master` as one of its file extensions, and we're also incorrectly picking up files in `.git` called `master` without a file extension. Removing the `.git` subdirectory from a repo and running with an absolute path doesn't show any ASP.NET.

**Comment by fahadhk** [comment] 2019-06-19 09:52
Thanks for feedback. 

Any fix coming up for this?

**Comment by dbaggerman** [comment] 2019-06-19 09:57
This is the first time it's been reported, so I'm still looking into it. I don't think it'll be too hard to fix though, we should have it patched soon.

**Comment by boyter** [comment] 2019-06-19 21:44
Thanks for reporting this. Could have sworn I verified this sometime back. I suspect I broke it when working on the .gitignore fixes a few months back.

```
# Regression issue https://github.com/boyter/scc/issues/82
a=$(./scc . | grep Total)
b=$(./scc ${PWD} | grep Total)
if [ "$a" == "$b" ]; then
    echo -e "${GREEN}PASSED git filter"
else
    echo -e "${RED}======================================================="
    echo -e "FAILED git filter"
    echo -e "================================================="
    exit
fi
```

A test replicating the issues which I dropped into `test-all.sh`. @dbaggerman let me know if you don't have the time to deal with this and ill look at it.

**Comment by boyter** [comment] 2019-06-20 10:02
@fahadhk thanks to the excellent work of @dbaggerman this looks like it has been resolved. If you build from master you should be able to confirm it. If so feel free to close this, otherwise ill do it in a few days.

**Comment by boyter** [comment] 2019-06-23 22:45
Closing down as promised.

**Closed by boyter** 2019-06-23 22:45 UTC
Labels: bug

**Comment by fahadhk** [comment] 2019-06-26 07:50
@boyter Thanks for closing and for the fix. I was not so active in the last few days.

**Comment by boyter** [comment] 2019-06-26 22:11
No problem.
